### ISSUE TITLE
unable to find org.codehaus.commons.compiler.properties in java 11

### ISSUE THREAD

**Issue by AshishAg24** [janino-compiler/janino#141]
This is being run on jetty. I can see the file within the jar and the jar is getting loaded. We are pulling in the most recent version for janino.jar and commons-compiler.jar (3.1.3). We tried 3.0.11 as well and the same error showed up.

```
cause: java.lang.IllegalStateException: Unable to instantiate java compiler
 ......
Caused by: java.lang.IllegalStateException: Unable to instantiate java compiler
        at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.compile(JaninoRelMetadataProvider.java:433)
        at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.load3(JaninoRelMetadataProvider.java:374)
        at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.lambda$static$0(JaninoRelMetadataProvider.java:109)
        at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3948)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3972)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
        at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.create(JaninoRelMetadataProvider.java:474)
        at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.revise(JaninoRelMetadataProvider.java:487)
        at org.apache.calcite.rel.metadata.RelMetadataQueryBase.revise(RelMetadataQueryBase.java:95)
        at org.apache.calcite.rel.metadata.RelMetadataQuery.collations(RelMetadataQuery.java:541)
        at org.apache.calcite.rel.metadata.RelMdCollation.filter(RelMdCollation.java:247)
        at org.apache.calcite.rel.logical.LogicalFilter.lambda$create$0(LogicalFilter.java:111)
        at org.apache.calcite.plan.RelTraitSet.replaceIfs(RelTraitSet.java:242)
        at org.apache.calcite.rel.logical.LogicalFilter.create(LogicalFilter.java:110)
        at org.apache.calcite.rel.core.RelFactories$FilterFactoryImpl.createFilter(RelFactories.java:339)
        at org.apache.calcite.tools.RelBuilder.filter(RelBuilder.java:1197)
        at org.apache.calcite.tools.RelBuilder.filter(RelBuilder.java:1155)
        .......
Caused by: java.lang.ClassNotFoundException: No implementation of org.codehaus.commons.compiler is on the class path. Typically, you'd have 'janino.jar', or 'commons-compiler-jdk.jar', or both on the classpath.
        at org.codehaus.commons.compiler.CompilerFactoryFactory.getDefaultCompilerFactory(CompilerFactoryFactory.java:64)
        at org.apache.calcite.rel.metadata.JaninoRelMetadataProvider.compile(JaninoRelMetadataProvider.java:431)
```

**Comment by aunkrig** [comment]
> This is being run on jetty. I can see the file within the jar and the jar is getting loaded.

Which "jar", and which "file within the jar" do you mean?

Janino dictates that a .jar file that implements the `ICompilerFactory` (namely `janino.jar` and `commons-compiler-jdk.jar`) contains one resource named `org.codehaus.commons.compiler.properties`. This has been working for ages.

The exception that you experience indicates that `commons-compiler.jar` is on the class path, while none of `janino.jar` and `commons-compiler-jdk.jar` are.

**Comment by Rajat-181** [comment]
@aunkrig The error mentioned above comes from the apache calcite (v1.26.0) code https://github.com/apache/calcite/blob/master/core/src/main/java/org/apache/calcite/rel/metadata/JaninoRelMetadataProvider.java#L427 when using JDK 11. Inside the janino code, `Thread.currentThread().getContextClassLoader()` is unable to find the  `org.codehaus.commons.compiler.properties` , I tried doing `CompilerFactoryFactory.class.getClassLoader().getResourceAsStream("org.codehaus.commons.compiler.properties");` and using this I was able to load the properties file, so definitely both `janino.jar` and `commons-compiler-jdk.jar` are on the classpath. Can you give some more insights on why the thread context class loader is used here?

**Comment by aunkrig** [comment]
Hey Rajat,
thank you for the detailed analysis!
Honestly, the concept of the „context class loader“ has always been unclear (to me), but it always seemed to be the better choice to use it and not the `ICompiler.class.getClassLoader()`. Any proposal how one should load resources?

**Comment by zmz0305** [comment]
Here's a good read about the context class loader. 
https://stackoverflow.com/questions/1771679/difference-between-threads-context-class-loader-and-normal-classloader

I think in general it's a bad idea to use the thread's context class loader because the thread may not have share the same class loader hierarchy?

**Comment by birschick-bq** [comment]
I'm also experiencing this issue (in Java 8). I concur with @Rajat-181 that his change also works for me.

**Comment by zmz0305** [comment]
We have tested with `CompilerFactoryFactory.class.getClassLoader().getResourceAsStream("org.codehaus.commons.compiler.properties")`, the properties file is able to load, but it was not able to load the actual `CompilerFactory` jar at this line https://github.com/janino-compiler/janino/blob/master/commons-compiler/src/main/java/org/codehaus/commons/compiler/CompilerFactoryFactory.java#L126

The only solution we current found is to do a Class.forName("org.codehaus.janino.CompilerFactory"), then the `CompilerFactory` class will be able to load.

**Comment by zmz0305** [comment]
One example fix that fixes @Rajat-181 and @AshishAg24 's issue:
<script src="https://gist.github.com/zmz0305/4c2d3cf9817f104423f7baf9d8a55bae.js"></script>

**Comment by zmz0305** [comment]
Based on this post https://stackoverflow.com/questions/8100376/class-forname-vs-classloader-loadclass-which-to-use-for-dynamic-loading

`(ICompilerFactory) Class.forName(compilerFactoryClassName).newInstance();` and `(ICompilerFactory) CompilerFactoryFactory.class.getClassLoader().loadClass( compilerFactoryClassName).newInstance();` should be essentially the same. I actually don't quite understand why the former works but not the latter.

**Comment by birschick-bq** [comment]
@aunkrig I have a proposed solution for this issue. Would you like me to push this and create a PR?

**Comment by aunkrig** [comment]
Ok, so I fixed this issue as follows:

Context class loaders are for cases where you forgot to pass an explicit class loader parameter (see [this article](https://stackoverflow.com/a/36228195)). Thus, I added duplicates of the relevant methode (`getDefaultCompilerFactory()`, `getAllCompilerFactories()` and `getCompilerFactory(className)`) with an extra `classLoader` parameter, and marked the original methods as deprecated.

You should only use the new methods, and for the `classLoader` parameter you would pass

* the `ClassLoader.getSystemClassLoader()` (to find the implementation on the application's class path), or
* `ICompilerFactory.class.getClassLoader()` (if the interface and the implementation are know to be loaded with the same class loader), or
* any other class loader of your liking.

Does this solve your problem(s)?

**Comment by birschick-bq** [comment]
@aunkrig Thanks for looking at this issue. Would it be possible to publish a pull request with the change so I could test it?

**Comment by zmz0305** [comment]
@aunkrig Thanks for the fix! Janino is used by https://github.com/apache/calcite and we are using calcite, so calcite needs to incorporate this change to fix the issue.
However, we were able to make it work by setting the thread's context class loader to the getClass().getClassloader() in our calling code.

**Comment by birschick-bq** [comment]
@aunkrig / @zmz0305 We are trying to use Calcite as a library for our JDBC driver. However, this is a blocking issue for us. When we try to create an uber JAR embedding calcite and janino, we are unable to get a working solution with the given state of the two libraries.

There is an "easy" fix if the Janino library uses the `CompilerFactoryFactory.class.getClassLoader()` instead of `Thread.currentThread().getContextClassLoader()`. In the three places in the `CompilerFactoryFactory` class. This does not require Calcite to explicitly make any change.

In any case, we're running out of time to get a solution for JDBC driver. Where there be a published solution in the next month?

**Comment by aunkrig** [comment]
Janino 3.1.4 is just out the door and the fix as part of it.
Please verify that the issue is now solved.

**Comment by birschick-bq** [comment]
@aunkrig Awesome. Thanks so much for getting that done. I'll work with the Calcite team (cc: @zmz0305) to integrate the change.

**Comment by birschick-bq** [comment]
@aunkrig One more question... Do you know when this release will get published on [Maven](https://mvnrepository.com/artifact/org.codehaus.janino/commons-compiler)?

**Comment by aunkrig** [comment]
Hey Bruce, JANINO 3.1.4 is already available on oss.sonatype.org and, from experience, two days later on maven.org.

**Comment by birschick-bq** [comment]
Hi @aunkrig 

I've finally had a chance to try out the change. 

Unfortunately, there is still a problem - with a small fix required...

Just need to call the correct overload of `getCompilerFactory` to pass the given `classLoader` down the line.

Diff given below...

```
 .../java/org/codehaus/commons/compiler/CompilerFactoryFactory.java    | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/commons-compiler/src/main/java/org/codehaus/commons/compiler/CompilerFactoryFactory.java b/commons-compiler/src/main/java/org/codehaus/commons/compiler/CompilerFactoryFactory.java
index f40e5bab..3bfa50f1 100644
--- a/commons-compiler/src/main/java/org/codehaus/commons/compiler/CompilerFactoryFactory.java
+++ b/commons-compiler/src/main/java/org/codehaus/commons/compiler/CompilerFactoryFactory.java
@@ -98,7 +98,7 @@ class CompilerFactoryFactory {
 
         return (
             CompilerFactoryFactory.defaultCompilerFactory
-            = CompilerFactoryFactory.getCompilerFactory(compilerFactoryClassName)
+            = CompilerFactoryFactory.getCompilerFactory(compilerFactoryClassName, classLoader)
         );
     }
 
@@ -150,7 +150,7 @@ class CompilerFactoryFactory {
                 throw new IllegalStateException(url.toString() + " does not specify the 'compilerFactory' property");
             }
 
-            factories.add(CompilerFactoryFactory.getCompilerFactory(compilerFactoryClassName));
+            factories.add(CompilerFactoryFactory.getCompilerFactory(compilerFactoryClassName, classLoader));
         }
         return (ICompilerFactory[]) factories.toArray(new ICompilerFactory[factories.size()]);
     }
```

**Comment by aunkrig** [comment]
Merged the related PR #150.
